### ISSUE TITLE
Release contains Java 17 bytecode

### ISSUE THREAD

**Issue by pk044** [MartinHH/scalacheck-derived#25]
hi! first off - thanks for releasing this great library!

I was wondering if it'd be possible to publish using JDK8 or JDK11? Our builds fail when ran under JDK8:

https://github.com/theiterators/kebs/actions/runs/5800590124/job/15723015359?pr=302#step:6:419

Thanks!

**Comment by MartinHH** [comment]
Sure, no problem. I just had forgotten about that aspect when configuring the project.

I'll publish a new release sometime within the next 24 hours.
